import './globals.css'
import App from './app'

export const metadata = {
  title: {
    template: '%s | Create Next App',
    default: 'Create Next App',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <App>
          {children}
        </App>
      </body>
    </html>
  )
}
