import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import "@/public/styles/uploadthing.css";
import "@/public/styles/index.css";
import Logo from "@/components/logo";
import { HolidayMarquee } from "@/components/holiday-banner";

export const metadata: Metadata = {
  title: {
    template: "%s | Create Next App",
    default: "Create Next App",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Logo className="absolute top-5 left-5 h-8 w-auto fill-zinc-50/80 z-[999]" />
        <main>
          <HolidayMarquee />
          {children}
        </main>
      </body>
    </html>
  );
}
